### ISSUE TITLE
Start date

### ISSUE THREAD

**Issue by emilirgi18** [grtfou/755-crawler#26]
Hey, there. I was just wondering if you could add start date as an argument so I can download from certain date range.

Thanks in advance!

**Comment by grtfou** [comment]
If you want to download posts between "start_date" and now, you could use it.
For example
```bash
# 2. Download from 200501 ~ today(200624)
$ python crawler.py https://7gogo.jp/kuranoo-narumi 200501
```

If you want to download post between "start_date" and "end_date", 
it doesn't support by 755 API now. 🤔

Thanks

**Comment by emilirgi18** [comment]
> If you want to download post between "start_date" and "end_date",

Yeah this is what I mean. Okay, then I'll close this issue now. Cheers!
